### ISSUE TITLE
can't find vangogh-sample 

### ISSUE THREAD

**Issue by hanburn** [PSPDFKit-labs/VanGogh#19]
I can not find the vangogh-sample project shown in the settings.gradle file of the project.
Please let me know where the sample project can verify the behavior. 

--from hanburn --

**Comment by skoric** [comment]
@hanburn the samples are work in progress (so gitignored for now). Keeping this issue opened until they're added to the repo. For now please see the documentation, the API itself is pretty straightforward: https://github.com/PSPDFKit-labs/VanGogh/wiki
